### PR TITLE
Support empty response bodies

### PR DESCRIPTION
**Pull request by lennym**
JSON.parse passed an empty string will throw a malformed JSON error. However many API endpoints return an empty body in many cases, which we want to be able to support.

If an API endpoint responds with an empty body then allow to continue.

### CODE REVIEW

**Comment by lennym** [comment]
FAO @gavboulton @sebinsua

**Comment by lennym** [comment]
I know the README docs are woefully incomplete, but given what's currently on npm then this is better than nothing.

**Comment by gavboulton** [comment]
Looks good to me.

**Comment by lennym** [comment]
Merge then?

**Comment by gavboulton** [comment]
@sebinsua do you have anything to add?

**Comment by sebinsua** [comment]
No, that looks good.

**Pull request merged**
