### PR TITLE
Content length of post should be byte length and not char length

### PR DESCRIPTION
**Pull request by HughePaul**

### CODE REVIEW

**Comment by gavboulton** [comment]
This looks fine to me. @JoeChapman @easternbloc @daniel-ac-martin

**Comment by gavboulton** [comment]
Anyone? @JoeChapman @easternbloc @daniel-ac-martin @joefitter

**Comment by joefitter** [comment]
:shipit:

**Comment by easternbloc** [comment]
Sorry for forgetting about this one. :shipit:

**Pull request merged**
